### ISSUE TITLE
Docs: Update Getting Started to v3.2

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/inveniosoftware.org#106]
Update code on `Scaffold` section of https://inveniosoftware.org/products/framework/ to point to 3.2
the pages below are not existing anymore due to remodeling of the website:
~~- Frontpage: https://inveniosoftware.org/#getstarted~~
~~- Guide: https://inveniosoftware.org/gettingstarted/~~
~~- (4) Needs to include example of adding a file.~~

**Comment by lnielsen** [comment]
```
# IMPORTANT: Choose ES6 for now (until new records-rest is released)
cookiecutter gh:inveniosoftware/cookiecutter-invenio-instance -c dev-v3.2
cd my-site
docker-compose up -d 
./scripts/bootstrap
./scripts/setup
./scripts/server
```

Upload a record

```
curl -k --header "Content-Type: application/json" \
--request POST \
--data '{"title":"Some title", "contributors": [{"name": "Doe, John"}]}' \
https://127.0.0.1:5000/api/records/?prettyprint=1
```

Upload a file
```
curl -k -H "Content-Type: application/octet-stream" -X PUT --data-binary @myfile.pdf https://127.0.0.1:5000/api/records/1/files/myfile.pdf
```

**Comment by roksys** [comment]
Since inveniosoftware.org was updated, pages mentioned in https://github.com/inveniosoftware/inveniosoftware.org/issues/106#issue-470910388 does not exist anymore. @kprzerwa can we close this ticket?
