### ISSUE TITLE
Add TU Tübingen as RDM partner

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/inveniosoftware.org#158]
See logo below. Add to:

- https://inveniosoftware.org/products/rdm/
- https://inveniordm.web.cern.ch

![UT_WBMW_Rot_RGB_01](https://user-images.githubusercontent.com/1698163/122011909-e5ed1e00-cdbc-11eb-8f1b-465290fe49dd.png)

**Comment by effervescent-shot** [comment]
- For https://inveniosoftware.org/products/rdm/ , should logo go only under "Brought to you by" or also under "Trusted by"?
