### ISSUE TITLE
footer: locally-provided gitter icon

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/inveniosoftware.org#18]
The chat information in the page footer is loaded via shields.io which can be "muted away" by privacy-oriented browser extensions such as Privacy Badger.  The footer then looks "empty":

![2016-10-06-104918_1366x768_scrot](https://cloud.githubusercontent.com/assets/517546/19146314/365829a8-8bb3-11e6-8c7a-39a37806533f.png)
  
It would be good to avoid using shields.io in order not to alienate these users.

**Comment by jbenito3** [comment]
@tiborsimko done on new-site branch.
