### ISSUE TITLE
header: adding Home menu?

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/inveniosoftware.org#25]
Let's ponder re-adding Home menu back to the header, which might be useful to mobile users, where the header menu is collapsed, for easier moving around pages?!

**Comment by jbenito3** [comment]
Even in mobile phones, the Invenio logo is there so anybody can click on it to go to 'home'. 
Sites like http://atom.io, not only they do not have the home in their mobile version, but you cannot even see the logo (home anchor) when opening the menu.
I think we can survive as it is. Better ideas are welcome :)

**Comment by tiborsimko** [comment]
My home page behaves similarly :) 

An alternative could be not to hide the menu items, but to list them down under the logo even for mobiles, which seemed to have been the choice of the http://projectblacklight.org/. 

Anyhow, the best solution depends on the number of menu items we'll have in the future. If we add "News", "Releases", "Packages", "Blog" and whatnot, we'd have too many items, so hiding would be useful. We could revive this at that moment...
